# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BotGripper.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x42otGripper.proto\x12\netrs.proto\"d\n\nBotGripper\x12)\n\x04side\x18\x01 \x01(\x0e\x32\x1b.etrs.proto.BotGripper.Side\x12\x0e\n\x06status\x18\x02 \x01(\x08\"\x1b\n\x04Side\x12\x08\n\x04Left\x10\x00\x12\t\n\x05Right\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BotGripper_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOTGRIPPER._serialized_start=32
  _BOTGRIPPER._serialized_end=132
  _BOTGRIPPER_SIDE._serialized_start=105
  _BOTGRIPPER_SIDE._serialized_end=132
# @@protoc_insertion_point(module_scope)
