# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KinectMode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10KinectMode.proto\x12\netrs.proto\"b\n\nKinectMode\x12)\n\x04mode\x18\x01 \x01(\x0e\x32\x1b.etrs.proto.KinectMode.Mode\")\n\x04Mode\x12\x12\n\x0eRECONSTRCUTION\x10\x00\x12\r\n\tREAL_TIME\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'KinectMode_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KINECTMODE._serialized_start=32
  _KINECTMODE._serialized_end=130
  _KINECTMODE_MODE._serialized_start=89
  _KINECTMODE_MODE._serialized_end=130
# @@protoc_insertion_point(module_scope)
