# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Mesh.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nMesh.proto\x12\netrs.proto\"{\n\x04Mesh\x12\x1a\n\x02v1\x18\x01 \x03(\x0b\x32\x0e.etrs.proto.V1\x12\x1a\n\x02v2\x18\x02 \x03(\x0b\x32\x0e.etrs.proto.V2\x12\x1a\n\x02v3\x18\x03 \x03(\x0b\x32\x0e.etrs.proto.V3\x12\t\n\x01r\x18\x04 \x03(\x02\x12\t\n\x01g\x18\x05 \x03(\x02\x12\t\n\x01\x62\x18\x06 \x03(\x02\"%\n\x02V1\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"%\n\x02V2\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"%\n\x02V3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Mesh_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESH._serialized_start=26
  _MESH._serialized_end=149
  _V1._serialized_start=151
  _V1._serialized_end=188
  _V2._serialized_start=190
  _V2._serialized_end=227
  _V3._serialized_start=229
  _V3._serialized_end=266
# @@protoc_insertion_point(module_scope)
