"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class BotCar(google.protobuf.message.Message):
    """底盘车"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MOVE_SEQUENCE_FIELD_NUMBER: builtins.int
    @property
    def move_sequence(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """第一个元素为1或0，1表示先前进，0表示先旋转。接着为动作序列（前进时间,旋转角度），以旋转角度结束。
        [1, 3, -90, 10, 0] 先前进
        [0, 45, 10, -90]   先后退
        """
    def __init__(
        self,
        *,
        move_sequence: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["move_sequence", b"move_sequence"]) -> None: ...

global___BotCar = BotCar
