"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class BotGripper(google.protobuf.message.Message):
    """夹爪"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Side:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SideEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[BotGripper._Side.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Left: BotGripper._Side.ValueType  # 0
        Right: BotGripper._Side.ValueType  # 1

    class Side(_Side, metaclass=_SideEnumTypeWrapper): ...
    Left: BotGripper.Side.ValueType  # 0
    Right: BotGripper.Side.ValueType  # 1

    SIDE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    side: global___BotGripper.Side.ValueType
    status: builtins.bool
    def __init__(
        self,
        *,
        side: global___BotGripper.Side.ValueType = ...,
        status: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["side", b"side", "status", b"status"]) -> None: ...

global___BotGripper = BotGripper
