# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BotLed.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x42otLed.proto\x12\netrs.proto\"V\n\x06\x42otLed\x12%\n\x04mode\x18\x01 \x01(\x0e\x32\x17.etrs.proto.BotLed.Mode\"%\n\x04Mode\x12\t\n\x05\x43LOSE\x10\x00\x12\t\n\x05GREEN\x10\x01\x12\x07\n\x03RED\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BotLed_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOTLED._serialized_start=28
  _BOTLED._serialized_end=114
  _BOTLED_MODE._serialized_start=77
  _BOTLED_MODE._serialized_end=114
# @@protoc_insertion_point(module_scope)
