"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class BotLed(google.protobuf.message.Message):
    """LED灯带"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Mode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[BotLed._Mode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        CLOSE: BotLed._Mode.ValueType  # 0
        GREEN: BotLed._Mode.ValueType  # 1
        RED: BotLed._Mode.ValueType  # 2

    class Mode(_Mode, metaclass=_ModeEnumTypeWrapper): ...
    CLOSE: BotLed.Mode.ValueType  # 0
    GREEN: BotLed.Mode.ValueType  # 1
    RED: BotLed.Mode.ValueType  # 2

    MODE_FIELD_NUMBER: builtins.int
    mode: global___BotLed.Mode.ValueType
    def __init__(
        self,
        *,
        mode: global___BotLed.Mode.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["mode", b"mode"]) -> None: ...

global___BotLed = BotLed
