"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class BotMotor(google.protobuf.message.Message):
    """舵机"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ANGLE_FIELD_NUMBER: builtins.int
    angle: builtins.int
    def __init__(
        self,
        *,
        angle: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["angle", b"angle"]) -> None: ...

global___BotMotor = BotMotor
