# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataMessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Mesh_pb2 as Mesh__pb2
import SoundSource_pb2 as SoundSource__pb2
import TempAndHumi_pb2 as TempAndHumi__pb2
import BotCar_pb2 as BotCar__pb2
import BotGripper_pb2 as BotGripper__pb2
import BotMotor_pb2 as BotMotor__pb2
import BotArm_pb2 as BotArm__pb2
import BotLed_pb2 as BotLed__pb2
import KinectMode_pb2 as KinectMode__pb2
import ObjectDetection_pb2 as ObjectDetection__pb2
import PointCloud_pb2 as PointCloud__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x44\x61taMessage.proto\x12\netrs.proto\x1a\nMesh.proto\x1a\x11SoundSource.proto\x1a\x11TempAndHumi.proto\x1a\x0c\x42otCar.proto\x1a\x10\x42otGripper.proto\x1a\x0e\x42otMotor.proto\x1a\x0c\x42otArm.proto\x1a\x0c\x42otLed.proto\x1a\x10KinectMode.proto\x1a\x15ObjectDetection.proto\x1a\x10PointCloud.proto\"\x86\x06\n\x0b\x44\x61taMessage\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.etrs.proto.DataMessage.Type\x12 \n\x04mesh\x18\x02 \x01(\x0b\x32\x10.etrs.proto.MeshH\x00\x12/\n\x0csound_source\x18\x03 \x01(\x0b\x32\x17.etrs.proto.SoundSourceH\x00\x12%\n\x07\x62ot_car\x18\x04 \x01(\x0b\x32\x12.etrs.proto.BotCarH\x00\x12-\n\x0b\x62ot_gripper\x18\x05 \x01(\x0b\x32\x16.etrs.proto.BotGripperH\x00\x12)\n\tbot_motor\x18\x06 \x01(\x0b\x32\x14.etrs.proto.BotMotorH\x00\x12%\n\x07\x62ot_arm\x18\x07 \x01(\x0b\x32\x12.etrs.proto.BotArmH\x00\x12%\n\x07\x62ot_led\x18\x08 \x01(\x0b\x32\x12.etrs.proto.BotLedH\x00\x12\x30\n\rtemp_and_humi\x18\t \x01(\x0b\x32\x17.etrs.proto.TempAndHumiH\x00\x12-\n\x0bkinect_mode\x18\n \x01(\x0b\x32\x16.etrs.proto.KinectModeH\x00\x12\x37\n\x10object_detection\x18\x0b \x01(\x0b\x32\x1b.etrs.proto.ObjectDetectionH\x00\x12-\n\x0bpoint_cloud\x18\x0c \x01(\x0b\x32\x16.etrs.proto.PointCloudH\x00\"\xd7\x01\n\x04Type\x12\t\n\x05OTHER\x10\x00\x12\x08\n\x04MESH\x10\x01\x12\x16\n\tEXIT_MESH\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x10\n\x0cSOUND_SOURCE\x10\x02\x12\x0b\n\x07\x42OT_CAR\x10\x03\x12\x0f\n\x0b\x42OT_GRIPPER\x10\x04\x12\r\n\tBOT_MOTOR\x10\x05\x12\x0b\n\x07\x42OT_ARM\x10\x06\x12\x0b\n\x07\x42OT_LED\x10\x07\x12\x11\n\rTEMP_AND_HUMI\x10\x08\x12\x0f\n\x0bKINECT_MODE\x10\t\x12\x14\n\x10OBJECT_DETECTION\x10\n\x12\x0f\n\x0bPOINT_CLOUD\x10\x0b\x42\x06\n\x04\x64\x61tab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DataMessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATAMESSAGE._serialized_start=219
  _DATAMESSAGE._serialized_end=993
  _DATAMESSAGE_TYPE._serialized_start=770
  _DATAMESSAGE_TYPE._serialized_end=985
# @@protoc_insertion_point(module_scope)
