"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class KinectMode(google.protobuf.message.Message):
    """KinectMode"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Mode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[KinectMode._Mode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        RECONSTRCUTION: KinectMode._Mode.ValueType  # 0
        """第三人称"""
        REAL_TIME: KinectMode._Mode.ValueType  # 1
        """第一人称"""

    class Mode(_Mode, metaclass=_ModeEnumTypeWrapper): ...
    RECONSTRCUTION: KinectMode.Mode.ValueType  # 0
    """第三人称"""
    REAL_TIME: KinectMode.Mode.ValueType  # 1
    """第一人称"""

    MODE_FIELD_NUMBER: builtins.int
    mode: global___KinectMode.Mode.ValueType
    def __init__(
        self,
        *,
        mode: global___KinectMode.Mode.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["mode", b"mode"]) -> None: ...

global___KinectMode = KinectMode
