"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Mesh(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    V1_FIELD_NUMBER: builtins.int
    V2_FIELD_NUMBER: builtins.int
    V3_FIELD_NUMBER: builtins.int
    R_FIELD_NUMBER: builtins.int
    G_FIELD_NUMBER: builtins.int
    B_FIELD_NUMBER: builtins.int
    @property
    def v1(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Vertex]: ...
    @property
    def v2(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Vertex]: ...
    @property
    def v3(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Vertex]: ...
    @property
    def r(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def g(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def b(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        v1: collections.abc.Iterable[global___Vertex] | None = ...,
        v2: collections.abc.Iterable[global___Vertex] | None = ...,
        v3: collections.abc.Iterable[global___Vertex] | None = ...,
        r: collections.abc.Iterable[builtins.float] | None = ...,
        g: collections.abc.Iterable[builtins.float] | None = ...,
        b: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["b", b"b", "g", b"g", "r", b"r", "v1", b"v1", "v2", b"v2", "v3", b"v3"]) -> None: ...

global___Mesh = Mesh

@typing_extensions.final
class Vertex(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    z: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["x", b"x", "y", b"y", "z", b"z"]) -> None: ...

global___Vertex = Vertex
