"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class ObjectDetection(google.protobuf.message.Message):
    """ObjectDetection"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECTS_FIELD_NUMBER: builtins.int
    @property
    def objects(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Object]: ...
    def __init__(
        self,
        *,
        objects: collections.abc.Iterable[global___Object] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["objects", b"objects"]) -> None: ...

global___ObjectDetection = ObjectDetection

@typing_extensions.final
class Object(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LABEL_FIELD_NUMBER: builtins.int
    BBOX_FIELD_NUMBER: builtins.int
    SCORE_FIELD_NUMBER: builtins.int
    label: builtins.str
    @property
    def bbox(self) -> global___BoundingBox: ...
    score: builtins.float
    def __init__(
        self,
        *,
        label: builtins.str = ...,
        bbox: global___BoundingBox | None = ...,
        score: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bbox", b"bbox"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bbox", b"bbox", "label", b"label", "score", b"score"]) -> None: ...

global___Object = Object

@typing_extensions.final
class BoundingBox(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    LENGTH_FIELD_NUMBER: builtins.int
    YAW_FIELD_NUMBER: builtins.int
    x: builtins.float
    """坐标"""
    y: builtins.float
    z: builtins.float
    width: builtins.float
    """长宽高"""
    height: builtins.float
    length: builtins.float
    yaw: builtins.float
    """旋转角度"""
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
        width: builtins.float = ...,
        height: builtins.float = ...,
        length: builtins.float = ...,
        yaw: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["height", b"height", "length", b"length", "width", b"width", "x", b"x", "y", b"y", "yaw", b"yaw", "z", b"z"]) -> None: ...

global___BoundingBox = BoundingBox
